import { ComponentType, SVGProps } from 'react';
import { 
  Loader2,
  User, 
  Camera, 
  LogOut, 
  Settings, 
  Edit, 
  X, 
  Check, 
  ChevronDown, 
  Plus, 
  Search, 
  Menu, 
  ArrowLeft, 
  ArrowRight, 
  AlertCircle, 
  CheckCircle, 
  Info, 
  XCircle, 
  Upload, 
  Download, 
  MoreHorizontal, 
  Filter, 
  Calendar, 
  Clock, 
  MapPin, 
  Phone, 
  Mail, 
  Lock, 
  Eye, 
  EyeOff, 
  Bell, 
  BellOff, 
  Star, 
  Heart, 
  Share2, 
  MessageSquare, 
  Send, 
  Image,
  FileText,
  FilePlus,
  FileMinus,
  FileCheck,
  FileX,
  FileSearch,
  FileSpreadsheet,
  FileType,
  FileUp,
  FileVideo,
  FileVolume2,
  FileWarning,
  FileArchive,
  FileAudio,
  FileBarChart,
  FileBox,
  FileClock,
  FileCog,
  FileDown,
  FileEdit,
  FileHeart,
  FileImage,
  FileInput,
  FileJson,
  FileKey,
  FileLineChart,
  FileLock,
  FileMusic,
  FilePieChart,
  FileQuestion,
  FileScan,
  FileSliders,
  FileStack,
  FileSymlink,
  FileTerminal,
  FileType2,
  FileVideo2,
  FileVolume,
  FileX2,
} from 'lucide-react';

export const Icons = {
  spinner: Loader2,
  user: User,
  camera: Camera,
  logout: LogOut,
  settings: Settings,
  edit: Edit,
  close: X,
  check: Check,
  chevronDown: ChevronDown,
  plus: Plus,
  search: Search,
  menu: Menu,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  alert: AlertCircle,
  checkCircle: CheckCircle,
  info: Info,
  xCircle: XCircle,
  upload: Upload,
  download: Download,
  more: MoreHorizontal,
  filter: Filter,
  calendar: Calendar,
  clock: Clock,
  mapPin: MapPin,
  phone: Phone,
  mail: Mail,
  lock: Lock,
  eye: Eye,
  eyeOff: EyeOff,
  bell: Bell,
  bellOff: BellOff,
  star: Star,
  heart: Heart,
  share: Share2,
  message: MessageSquare,
  send: Send,
  image: Image,
  fileText: FileText,
  filePlus: FilePlus,
  fileMinus: FileMinus,
  fileCheck: FileCheck,
  fileX: FileX,
  fileSearch: FileSearch,
  fileSpreadsheet: FileSpreadsheet,
  fileType: FileType,
  fileUp: FileUp,
  fileVideo: FileVideo,
  fileVolume: FileVolume2,
  fileWarning: FileWarning,
  fileArchive: FileArchive,
  fileAudio: FileAudio,
  fileBarChart: FileBarChart,
  fileBox: FileBox,
  fileClock: FileClock,
  fileCog: FileCog,
  fileDown: FileDown,
  fileEdit: FileEdit,
  fileHeart: FileHeart,
  fileImage: FileImage,
  fileInput: FileInput,
  fileJson: FileJson,
  fileKey: FileKey,
  fileLineChart: FileLineChart,
  fileLock: FileLock,
  fileMusic: FileMusic,
  filePieChart: FilePieChart,
  fileQuestion: FileQuestion,
  fileScan: FileScan,
  fileSliders: FileSliders,
  fileStack: FileStack,
  fileSymlink: FileSymlink,
  fileTerminal: FileTerminal,
  fileType2: FileType2,
  fileVideo2: FileVideo2,
  fileVolume2: FileVolume,
  fileX2: FileX2,
} as const;

export type IconName = keyof typeof Icons;

interface IconProps extends SVGProps<SVGSVGElement> {
  name: IconName;
  className?: string;
}

export function Icon({ name, className, ...props }: IconProps) {
  const IconComponent = Icons[name] as ComponentType<SVGProps<SVGSVGElement>>;
  
  if (!IconComponent) {
    console.warn(`Icon '${name}' not found`);
    return null;
  }

  return <IconComponent className={className} {...props} />;
}
